name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: 45 19 1 * *

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19.3
      - name: Build
        shell: bash
        run: |
          set -euo pipefail
          echo "dash dash/sh boolean false" | sudo debconf-set-selections
          sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash || true
          ./start build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: build
      - uses: actions/deploy-pages@v1
